name: imersao-full-cycle
include:
  - ../../backend/nestjs-api/docker-compose.yaml

services:
  next_js:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3001:3000
    depends_on:
      - nest_js
